services:
  blog-server:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements.txt
    restart: always
    ports:
      - 9000:8000
    env_file: .env
    command: 'sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"'
    volumes:
      - ./:/app

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
