# Generated by Django 5.0.6 on 2024-06-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('normal', 'Normal')], default='normal', max_length=50),
        ),
    ]
