# Generated by Django 5.0.6 on 2024-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_topic_topicblogmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
