# Generated by Django 5.0.6 on 2024-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0007_alter_blog_title_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_read_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
